import { expect, test } from '@playwright/test'
import { prepareIsolatedSession } from './support/isolated-session'

test.setTimeout(90_000)
test('多实例菜单内部点击、连续开关和卸载保持正确监听', async ({ page }, info) => {
  await prepareIsolatedSession(page)
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/tests/e2e/fixtures/context-menu-lifecycle.html')
  await page.clock.install()
  const open = page.getByRole('button', { name: '打开菜单', exact: true })
  const group = page.getByRole('menuitem', { name: '更多操作', exact: true })
  const advance = () => page.clock.runFor(200)
  await open.click()
  await advance()
  await group.click()
  await expect(group).toBeVisible()
  await expect(page.getByRole('menuitem', { name: '不可用操作' })).toBeDisabled()
  await page.screenshot({ path: info.outputPath('context-menu.png') })
  await page.keyboard.press('Escape')
  await advance()
  await expect(group).toBeHidden()
  await expect(page.getByLabel('关闭次数')).toHaveText('1')
  await open.click()
  await page.getByRole('button', { name: '关闭菜单', exact: true }).click()
  await open.click()
  await advance()
  await page.getByRole('menuitem', { name: '选择操作', exact: true }).click()
  await advance()
  await expect(group).toBeHidden()
  await expect(page.getByLabel('选择次数')).toHaveText('1')
  await open.click()
  await page.getByRole('button', { name: '切换组件', exact: true }).click()
  await advance()
  const count = await page.getByLabel('关闭次数').textContent()
  await page.keyboard.press('Escape')
  await expect(page.getByLabel('关闭次数')).toHaveText(count ?? '')
  await page.getByRole('button', { name: '切换组件', exact: true }).click()
  await open.click()
  await advance()
  await group.click()
  await expect(group).toBeVisible()
  await page.getByRole('button', { name: '关闭菜单', exact: true }).click()
  await advance()
  await expect(group).toBeHidden()
  expect(errors).toEqual([])
})
