import { expect, test } from '@playwright/test'
import { prepareIsolatedSession } from './support/isolated-session'

test.use({ storageState: { cookies: [], origins: [] } })
test.setTimeout(120_000)

test('顶部栏通知点击边界、引导计时与卸载后清理', async ({ page }, info) => {
  await prepareIsolatedSession(page)
  await page.route('**/rest/v1/**', (route) => route.fulfill({ json: [] }))
  const time = new Date('2026-10-10T01:00:00Z')
  await page.clock.install({ time })
  await page.clock.pauseAt(new Date('2026-10-10T02:00:00Z'))
  await page.goto('/tests/e2e/fixtures/shell-component-lifecycle.html?mode=header')
  const header = page.locator('.art-header-bar')
  await expect(header).toBeVisible()
  const guide = page.getByLabel('设置引导状态')
  await expect(guide).toHaveText('true')
  await page.getByRole('button', { name: '打开通知中心', exact: true }).click()
  await page.clock.runFor(20)
  const panel = page.locator('.art-notification-panel')
  await expect(panel).toBeVisible()
  await panel.click({ position: { x: 20, y: 20 } })
  await expect(panel).toBeVisible()
  await page.screenshot({ path: info.outputPath('header-notification.png'), fullPage: true })
  await page.getByLabel('当前路径').click()
  await page.clock.runFor(300)
  await expect(panel).toBeHidden()
  await page.getByRole('button', { name: '切换组件', exact: true }).click()
  await expect(header).toHaveCount(0)
  await page.clock.runFor(8000)
  await expect(guide).toHaveText('true')
  await page.getByRole('button', { name: '切换组件', exact: true }).click()
  await expect(header).toBeVisible()
  await page.clock.runFor(7999)
  await expect(guide).toHaveText('true')
  await page.clock.runFor(1)
  await expect(guide).toHaveText('false')
  await page.getByRole('button', { name: '打开通知中心', exact: true }).click()
  await page.clock.runFor(20)
  await expect(panel).toBeVisible()
  await page.getByLabel('当前路径').click()
  await page.clock.runFor(300)
  await expect(panel).toBeHidden()
})
