-- Connect the approval engine to a tenant-safe, persistent header notification inbox.
-- Workflow entities remain authoritative; notifications are a read/delivery projection only.

create table public.sys_notification (
  id uuid primary key default gen_random_uuid(),
  recipient_user_id uuid not null references public.sys_user(id) on delete cascade,
  category text not null,
  title text not null,
  content text,
  severity text not null default 'info',
  source_type text not null,
  source_id uuid not null,
  business_type text,
  business_id uuid,
  instance_id uuid references public.wf_instance(id) on delete cascade,
  route_path text not null default '/workflow/workbench',
  route_query jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  read_at timestamptz,
  create_by text,
  create_time timestamptz not null default now(),
  update_by text,
  update_time timestamptz not null default now(),
  tenant_id uuid not null default app_private.current_user_tenant_id(),
  constraint sys_notification_category_check
    check (category in ('notice', 'message', 'todo')),
  constraint sys_notification_severity_check
    check (severity in ('info', 'success', 'warning', 'danger')),
  constraint sys_notification_title_not_blank check (btrim(title) <> ''),
  constraint sys_notification_source_type_not_blank check (btrim(source_type) <> ''),
  constraint sys_notification_route_query_object check (jsonb_typeof(route_query) = 'object'),
  constraint sys_notification_read_state_check
    check ((is_read and read_at is not null) or (not is_read and read_at is null)),
  constraint sys_notification_source_unique
    unique (recipient_user_id, category, source_type, source_id)
);
comment on table public.sys_notification is
  'Tenant-scoped per-user notification projection generated by trusted business workflows.';
create index sys_notification_recipient_created_idx
  on public.sys_notification(tenant_id, recipient_user_id, create_time desc);
create index sys_notification_recipient_unread_idx
  on public.sys_notification(tenant_id, recipient_user_id, category, create_time desc)
  where is_read = false;
create index sys_notification_business_idx
  on public.sys_notification(tenant_id, business_type, business_id)
  where business_type is not null and business_id is not null;
create index sys_notification_instance_id_idx
  on public.sys_notification(instance_id)
  where instance_id is not null;
create trigger sys_notification_create_audit
before insert on public.sys_notification
for each row execute function public.trg_set_create_time_and_by('true', 'true');
create trigger sys_notification_update_audit
before update on public.sys_notification
for each row execute function public.trg_set_update_time_and_by();
alter table public.sys_notification enable row level security;
create policy own_notification_select
on public.sys_notification
for select
to authenticated
using (
  (select auth.uid()) is not null
  and tenant_id = (select app_private.current_user_tenant_id())
  and recipient_user_id = (select app_private.current_app_user_id())
);
revoke all on table public.sys_notification from public, anon, authenticated;
grant select on table public.sys_notification to authenticated;
grant all on table public.sys_notification to service_role;
create or replace function app_private.enqueue_user_notification(
  p_recipient_user_id uuid,
  p_tenant_id uuid,
  p_category text,
  p_title text,
  p_content text,
  p_severity text,
  p_source_type text,
  p_source_id uuid,
  p_business_type text default null,
  p_business_id uuid default null,
  p_instance_id uuid default null,
  p_route_path text default '/workflow/workbench',
  p_route_query jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_notification_id uuid;
begin
  if p_recipient_user_id is null or p_tenant_id is null then
    raise exception '通知接收人和租户不能为空';
  end if;
  if p_category not in ('notice', 'message', 'todo') then
    raise exception '不支持的通知分类';
  end if;
  if p_severity not in ('info', 'success', 'warning', 'danger') then
    raise exception '不支持的通知级别';
  end if;
  if btrim(coalesce(p_title, '')) = '' or btrim(coalesce(p_source_type, '')) = '' then
    raise exception '通知标题和来源不能为空';
  end if;
  if coalesce(jsonb_typeof(p_route_query), 'null') <> 'object' then
    raise exception '通知路由参数必须是对象';
  end if;
  if not exists (
    select 1
    from public.sys_user u
    where u.id = p_recipient_user_id
      and u.tenant_id = p_tenant_id
      and u.status = '1'
  ) then
    raise exception '通知接收人不存在、已停用或不属于当前租户';
  end if;

  insert into public.sys_notification(
    recipient_user_id,
    category,
    title,
    content,
    severity,
    source_type,
    source_id,
    business_type,
    business_id,
    instance_id,
    route_path,
    route_query,
    tenant_id
  ) values (
    p_recipient_user_id,
    p_category,
    btrim(p_title),
    nullif(btrim(coalesce(p_content, '')), ''),
    p_severity,
    btrim(p_source_type),
    p_source_id,
    nullif(btrim(coalesce(p_business_type, '')), ''),
    p_business_id,
    p_instance_id,
    coalesce(nullif(btrim(coalesce(p_route_path, '')), ''), '/workflow/workbench'),
    coalesce(p_route_query, '{}'::jsonb),
    p_tenant_id
  )
  on conflict (recipient_user_id, category, source_type, source_id) do nothing
  returning id into v_notification_id;

  if v_notification_id is null then
    select n.id into v_notification_id
    from public.sys_notification n
    where n.recipient_user_id = p_recipient_user_id
      and n.category = p_category
      and n.source_type = p_source_type
      and n.source_id = p_source_id;
  end if;

  return v_notification_id;
end;
$$;
revoke all on function app_private.enqueue_user_notification(
  uuid, uuid, text, text, text, text, text, uuid, text, uuid, uuid, text, jsonb
) from public, anon, authenticated;
grant execute on function app_private.enqueue_user_notification(
  uuid, uuid, text, text, text, text, text, uuid, text, uuid, uuid, text, jsonb
) to service_role;
create or replace function app_private.trg_notify_workflow_task_created()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_instance public.wf_instance;
begin
  select * into v_instance
  from public.wf_instance i
  where i.id = new.instance_id;

  if not found then
    raise exception '审批任务关联的流程实例不存在';
  end if;

  perform app_private.enqueue_user_notification(
    new.assignee_user_id,
    new.tenant_id,
    'todo',
    '待审批：' || v_instance.business_title,
    v_instance.initiator_name_snapshot || ' 提交至“' || new.node_name || '”节点',
    case when new.due_at is not null and new.due_at <= now() + interval '4 hours'
      then 'danger' else 'warning' end,
    'workflow_task',
    new.id,
    v_instance.business_type,
    v_instance.business_id,
    v_instance.id,
    '/workflow/workbench',
    jsonb_build_object('tab', 'pending', 'instanceId', v_instance.id)
  );

  return new;
end;
$$;
create or replace function app_private.trg_sync_workflow_task_notification()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status = 'pending' and new.status <> 'pending' then
    update public.sys_notification n
    set is_read = true,
        read_at = coalesce(n.read_at, now())
    where n.recipient_user_id = new.assignee_user_id
      and n.category = 'todo'
      and n.source_type = 'workflow_task'
      and n.source_id = new.id
      and n.is_read = false;
  end if;
  return new;
end;
$$;
create or replace function app_private.trg_notify_workflow_action_created()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_instance public.wf_instance;
  v_action_label text;
  v_severity text;
begin
  if new.action not in ('approve', 'reject', 'cancel') then
    return new;
  end if;

  select * into v_instance
  from public.wf_instance i
  where i.id = new.instance_id;

  if not found or new.actor_user_id is null
     or new.actor_user_id = v_instance.initiator_user_id then
    return new;
  end if;

  v_action_label := case new.action
    when 'approve' then '通过了'
    when 'reject' then '驳回了'
    else '终止了'
  end;
  v_severity := case new.action
    when 'approve' then 'success'
    when 'reject' then 'danger'
    else 'warning'
  end;

  perform app_private.enqueue_user_notification(
    v_instance.initiator_user_id,
    v_instance.tenant_id,
    'message',
    new.actor_name_snapshot || v_action_label || '审批节点',
    coalesce(nullif(new.node_name, '') || ' · ', '')
      || v_instance.business_title
      || coalesce('：' || nullif(btrim(coalesce(new.comment, '')), ''), ''),
    v_severity,
    'workflow_action',
    new.id,
    v_instance.business_type,
    v_instance.business_id,
    v_instance.id,
    '/workflow/workbench',
    jsonb_build_object('tab', 'initiated', 'instanceId', v_instance.id)
  );

  return new;
end;
$$;
create or replace function app_private.trg_notify_workflow_instance_finished()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_title text;
  v_severity text;
begin
  if old.status = new.status or new.status = 'running' then
    return new;
  end if;

  v_title := case new.status
    when 'approved' then '审批已通过：'
    when 'rejected' then '审批已驳回：'
    when 'withdrawn' then '审批已撤回：'
    when 'cancelled' then '审批已取消：'
    else '审批状态已更新：'
  end || new.business_title;
  v_severity := case new.status
    when 'approved' then 'success'
    when 'rejected' then 'danger'
    when 'cancelled' then 'warning'
    else 'info'
  end;

  perform app_private.enqueue_user_notification(
    new.initiator_user_id,
    new.tenant_id,
    'notice',
    v_title,
    coalesce(nullif(btrim(coalesce(new.finish_comment, '')), ''), '流程处理完成，可进入审批工作台查看完整记录。'),
    v_severity,
    'workflow_instance',
    new.id,
    new.business_type,
    new.business_id,
    new.id,
    '/workflow/workbench',
    jsonb_build_object('tab', 'initiated', 'instanceId', new.id)
  );

  return new;
end;
$$;
revoke all on function app_private.trg_notify_workflow_task_created()
  from public, anon, authenticated;
revoke all on function app_private.trg_sync_workflow_task_notification()
  from public, anon, authenticated;
revoke all on function app_private.trg_notify_workflow_action_created()
  from public, anon, authenticated;
revoke all on function app_private.trg_notify_workflow_instance_finished()
  from public, anon, authenticated;
create trigger wf_task_notification_created
after insert on public.wf_task
for each row execute function app_private.trg_notify_workflow_task_created();
create trigger wf_task_notification_synced
after update of status on public.wf_task
for each row execute function app_private.trg_sync_workflow_task_notification();
create trigger wf_action_notification_created
after insert on public.wf_action
for each row execute function app_private.trg_notify_workflow_action_created();
create trigger wf_instance_notification_finished
after update of status on public.wf_instance
for each row execute function app_private.trg_notify_workflow_instance_finished();
create or replace function app_private.get_header_notification_center(
  p_limit integer default 20
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select app_private.current_app_user_id());
  v_tenant_id uuid := (select app_private.current_user_tenant_id());
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 50);
  v_result jsonb;
begin
  if (select auth.uid()) is null or v_user_id is null or v_tenant_id is null then
    raise exception '当前登录用户未绑定业务账号' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'notices', coalesce((
      select jsonb_agg(row_data order by create_time desc)
      from (
        select jsonb_build_object(
          'id', n.id,
          'category', n.category,
          'title', n.title,
          'content', n.content,
          'severity', n.severity,
          'isRead', n.is_read,
          'createdAt', n.create_time,
          'routePath', n.route_path,
          'routeQuery', n.route_query,
          'instanceId', n.instance_id
        ) row_data, n.create_time
        from public.sys_notification n
        where n.tenant_id = v_tenant_id
          and n.recipient_user_id = v_user_id
          and n.category = 'notice'
        order by n.create_time desc
        limit v_limit
      ) rows
    ), '[]'::jsonb),
    'messages', coalesce((
      select jsonb_agg(row_data order by create_time desc)
      from (
        select jsonb_build_object(
          'id', n.id,
          'category', n.category,
          'title', n.title,
          'content', n.content,
          'severity', n.severity,
          'isRead', n.is_read,
          'createdAt', n.create_time,
          'routePath', n.route_path,
          'routeQuery', n.route_query,
          'instanceId', n.instance_id
        ) row_data, n.create_time
        from public.sys_notification n
        where n.tenant_id = v_tenant_id
          and n.recipient_user_id = v_user_id
          and n.category = 'message'
        order by n.create_time desc
        limit v_limit
      ) rows
    ), '[]'::jsonb),
    'todos', coalesce((
      select jsonb_agg(row_data order by create_time desc)
      from (
        select jsonb_build_object(
          'id', n.id,
          'category', n.category,
          'title', n.title,
          'content', n.content,
          'severity', n.severity,
          'isRead', n.is_read,
          'createdAt', n.create_time,
          'routePath', n.route_path,
          'routeQuery', n.route_query,
          'instanceId', n.instance_id
        ) row_data, n.create_time
        from public.sys_notification n
        where n.tenant_id = v_tenant_id
          and n.recipient_user_id = v_user_id
          and n.category = 'todo'
          and n.is_read = false
        order by n.create_time desc
        limit v_limit
      ) rows
    ), '[]'::jsonb),
    'unreadNoticeCount', (
      select count(*) from public.sys_notification n
      where n.tenant_id = v_tenant_id and n.recipient_user_id = v_user_id
        and n.category = 'notice' and n.is_read = false
    ),
    'unreadMessageCount', (
      select count(*) from public.sys_notification n
      where n.tenant_id = v_tenant_id and n.recipient_user_id = v_user_id
        and n.category = 'message' and n.is_read = false
    ),
    'pendingTodoCount', (
      select count(*) from public.sys_notification n
      where n.tenant_id = v_tenant_id and n.recipient_user_id = v_user_id
        and n.category = 'todo' and n.is_read = false
    )
  ) into v_result;

  return v_result || jsonb_build_object(
    'totalUnreadCount',
    coalesce((v_result ->> 'unreadNoticeCount')::integer, 0)
      + coalesce((v_result ->> 'unreadMessageCount')::integer, 0)
      + coalesce((v_result ->> 'pendingTodoCount')::integer, 0)
  );
end;
$$;
create or replace function app_private.mark_header_notifications_read(
  p_category text default null,
  p_notification_ids uuid[] default null
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := (select app_private.current_app_user_id());
  v_tenant_id uuid := (select app_private.current_user_tenant_id());
  v_count integer;
begin
  if (select auth.uid()) is null or v_user_id is null or v_tenant_id is null then
    raise exception '当前登录用户未绑定业务账号' using errcode = '42501';
  end if;
  if p_category is not null and p_category not in ('notice', 'message') then
    raise exception '待办事项需完成审批后自动归档';
  end if;

  update public.sys_notification n
  set is_read = true,
      read_at = coalesce(n.read_at, now())
  where n.tenant_id = v_tenant_id
    and n.recipient_user_id = v_user_id
    and n.category in ('notice', 'message')
    and n.is_read = false
    and (p_category is null or n.category = p_category)
    and (p_notification_ids is null or n.id = any(p_notification_ids));

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
revoke all on function app_private.get_header_notification_center(integer)
  from public, anon;
revoke all on function app_private.mark_header_notifications_read(text, uuid[])
  from public, anon;
grant execute on function app_private.get_header_notification_center(integer)
  to authenticated, service_role;
grant execute on function app_private.mark_header_notifications_read(text, uuid[])
  to authenticated, service_role;
create or replace function public.get_header_notification_center(
  p_limit integer default 20
)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select app_private.get_header_notification_center(p_limit)
$$;
create or replace function public.mark_header_notifications_read(
  p_category text default null,
  p_notification_ids uuid[] default null
)
returns integer
language sql
security invoker
set search_path = ''
as $$
  select app_private.mark_header_notifications_read(p_category, p_notification_ids)
$$;
revoke all on function public.get_header_notification_center(integer)
  from public, anon;
revoke all on function public.mark_header_notifications_read(text, uuid[])
  from public, anon;
grant execute on function public.get_header_notification_center(integer)
  to authenticated, service_role;
grant execute on function public.mark_header_notifications_read(text, uuid[])
  to authenticated, service_role;
-- Backfill only active workflow projections; the current project has no runtime rows yet,
-- but these statements keep the migration safe for another environment with existing data.
insert into public.sys_notification(
  recipient_user_id,
  category,
  title,
  content,
  severity,
  source_type,
  source_id,
  business_type,
  business_id,
  instance_id,
  route_path,
  route_query,
  tenant_id
)
select
  t.assignee_user_id,
  'todo',
  '待审批：' || i.business_title,
  i.initiator_name_snapshot || ' 提交至“' || t.node_name || '”节点',
  case when t.due_at is not null and t.due_at <= now() + interval '4 hours'
    then 'danger' else 'warning' end,
  'workflow_task',
  t.id,
  i.business_type,
  i.business_id,
  i.id,
  '/workflow/workbench',
  jsonb_build_object('tab', 'pending', 'instanceId', i.id),
  t.tenant_id
from public.wf_task t
join public.wf_instance i on i.id = t.instance_id
where t.status = 'pending'
on conflict (recipient_user_id, category, source_type, source_id) do nothing;
